version: '3.8'
name: elearning

services:
  httpd:
    container_name: elearning-httpd
    image: httpd:2.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/httpd/logs/:/var/log/apache2
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd/vhosts/:/usr/local/apache2/conf/vhosts
    networks:
      - devstack
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  app:
    container_name: elearning-app
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
      target: elearning_php_fpm_dev
      args:
        DOCKER_USER_NAME: ${DOCKER_USER_NAME}
        DOCKER_HOST_UID: ${DOCKER_HOST_UID}
        DOCKER_GROUP_NAME: ${DOCKER_GROUP_NAME}
        DOCKER_HOST_GID: ${DOCKER_HOST_GID}
        SOURCE_ROOT: ${SOURCE_ROOT}
    depends_on:
      - httpd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/alvin/Documents/PRIVE/elearning:/var/www/elearning
    networks:
      - elearning
      - devstack
    restart: unless-stopped
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  front:
    container_name: elearning-front
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
      args:
        DOCKER_USER_NAME: ${DOCKER_USER_NAME}
        DOCKER_HOST_UID: ${DOCKER_HOST_UID}
        DOCKER_GROUP_NAME: ${DOCKER_GROUP_NAME}
        DOCKER_HOST_GID: ${DOCKER_HOST_GID}
        SOURCE_ROOT: ${SOURCE_ROOT}
    depends_on:
      - app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/alvin/Documents/PRIVE/elearning:/var/www/elearning
    networks:
      - elearning
      - devstack
    expose:
      - 8080
    restart: unless-stopped

networks:
  elearning:
    driver: bridge
  devstack:
    name: devstack
    driver: bridge
    external: true
volumes:
  elearning_data:
    driver: local
  elearning_redis:
    driver: local
